language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip insall coverage
  - pip install coveralls
  - pip install pytest

script:
  - py.test --cov=app tests/

after_success:
  - coveralls
